In [1]:
#import the libraries:
import pandas as pd 
import numpy as np
from sklearn import metrics
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import BayesianRidge 
from sklearn.linear_model import ElasticNet

# Models:

In [2]:
# import the clean datasets
%store -r dmd_cl1
#%store -r dmd_cl2
#%store -r dmd_cl3
#%store -r dmd_cl4

In [3]:
# LETS START WITH CL1

In [4]:
X = dmd_cl1.drop(columns = 'price')
y = dmd_cl1['price']

#### Lets divide the dataset into train and test

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test, y_train, y_test = train_test_split( X, y, train_size=0.8)

In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

## 1. LINEAR REGRESSION

In [8]:
#Train the model
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [9]:
y_pred_train_lr = lr.predict(X_train)
y_pred_test_lr = lr.predict(X_test)

In [10]:
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train, y_pred_train_lr ))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train, y_pred_train_lr ))
print('TRAIN : R2 Score:', r2_score(y_train, y_pred_train_lr ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train, y_pred_train_lr )))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred_test_lr ))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred_test_lr ))
print('TEST : R2 Score:', r2_score(y_test, y_pred_test_lr))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test_lr )))

TRAIN : Mean Absolute Error: 804.7498259567283
TRAIN : Mean Squared Error: 1338394.2895621923
TRAIN : R2 Score: 0.9162317782061482
TRAIN : Root Mean Squared Error: 1156.8899211083967
----------------------------------------------------------
TEST : Mean Absolute Error: 808.389232592082
TEST : Mean Squared Error: 1364594.29385483
TEST : R2 Score: 0.9171649098856017
TEST : Root Mean Squared Error: 1168.1585054498512


#### Cross Validation:

In [11]:
scores_lr = cross_val_score(lr, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error')
scores_lr

array([-1163.73988521, -1143.00303416, -1168.67356114])

## 2. LASSO

In [12]:
lasso = Lasso()
lasso.fit(X_train, y_train)

Lasso()

In [13]:
y_pred_train_lasso = lasso.predict(X_train)
y_pred_test_lasso = lasso.predict(X_test)

In [14]:
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train, y_pred_train_lasso ))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train, y_pred_train_lasso ))
print('TRAIN : R2 Score:', r2_score(y_train, y_pred_train_lasso ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train, y_pred_train_lasso )))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred_test_lasso ))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred_test_lasso ))
print('TEST : R2 Score:', r2_score(y_test, y_pred_test_lasso))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test_lasso )))

TRAIN : Mean Absolute Error: 802.7689295299829
TRAIN : Mean Squared Error: 1338887.7115157922
TRAIN : R2 Score: 0.9162008956179831
TRAIN : Root Mean Squared Error: 1157.1031550885134
----------------------------------------------------------
TEST : Mean Absolute Error: 806.8379857642678
TEST : Mean Squared Error: 1365695.0251119619
TEST : R2 Score: 0.9170980920971301
TEST : Root Mean Squared Error: 1168.6295499909122


#### Cross Validation:

In [15]:
scores_lasso = cross_val_score(lasso, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error')
scores_lasso

array([-1164.28000245, -1142.245726  , -1169.50015585])

## 3. RIDGE

In [16]:
ridge = Ridge(alpha = 1)
ridge.fit(X_train, y_train)

Ridge(alpha=1)

In [17]:
y_pred_train_ridge = ridge.predict(X_train)
y_pred_test_ridge = ridge.predict(X_test)

In [19]:
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train, y_pred_train_ridge ))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train, y_pred_train_ridge ))
print('TRAIN : R2 Score:', r2_score(y_train, y_pred_train_ridge ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train, y_pred_train_ridge )))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred_test_ridge ))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred_test_ridge ))
print('TEST : R2 Score:', r2_score(y_test, y_pred_test_ridge))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test_ridge )))

TRAIN : Mean Absolute Error: 804.6677781259592
TRAIN : Mean Squared Error: 1338395.068254835
TRAIN : R2 Score: 0.9162317294688677
TRAIN : Root Mean Squared Error: 1156.8902576540418
----------------------------------------------------------
TEST : Mean Absolute Error: 808.3238710898611
TEST : Mean Squared Error: 1364620.4642571337
TEST : R2 Score: 0.9171633212613176
TEST : Root Mean Squared Error: 1168.169706959196


#### Cross validation : 

In [20]:
scores_ridge = cross_val_score(lasso, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error')
scores_ridge

array([-1164.28000245, -1142.245726  , -1169.50015585])

## 4. DECISSION TREE

In [21]:
tree = DecisionTreeClassifier(max_depth = 3)
tree.fit(X_train, y_train)
y_pred_train_tree = tree.predict(X_train)
y_pred_test_tree = tree.predict(X_test)

In [23]:
from sklearn import metrics
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train, y_pred_train_tree))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train, y_pred_train_tree))
print('TRAIN : R2 Score:', r2_score(y_train, y_pred_train_tree ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train, y_pred_train_tree)))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred_test_tree ))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred_test_tree ))
print('TRAIN : R2 Score:', r2_score(y_test, y_pred_test_tree ))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test_tree )))

TRAIN : Mean Absolute Error: 3187.9112285255223
TRAIN : Mean Squared Error: 25714229.218730688
TRAIN : R2 Score: -0.6094175485141906
TRAIN : Root Mean Squared Error: 5070.919957831191
----------------------------------------------------------
TEST : Mean Absolute Error: 3230.177604746014
TEST : Mean Squared Error: 26463896.380793475
TRAIN : R2 Score: -0.6064402814470027
TEST : Root Mean Squared Error: 5144.307181807233


#### Cross validation:

In [25]:
scores_tree = cross_val_score(tree, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error')
scores_tree

/home/ubuntu/.local/lib/python3.8/site-packages/sklearn/model_selection/_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(("The least populated class in y has only %d"


array([-5102.42699543, -5019.96921589, -5090.2450107 ])

## 5. RANDOM FOREST

In [26]:
randforest = RandomForestRegressor(n_estimators=20, random_state=10)
randforest.fit(X_train, y_train)
y_pred_train_randforest = randforest.predict(X_train)
y_pred_test_randforest = randforest.predict(X_test)

In [27]:
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train, y_pred_train_randforest))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train, y_pred_train_randforest))
print('TRAIN : R2 Score:', r2_score(y_train, y_pred_train_randforest ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train, y_pred_train_randforest)))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred_test_randforest ))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred_test_randforest ))
print('TRAIN : R2 Score:', r2_score(y_test, y_pred_test_randforest ))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test_randforest )))

TRAIN : Mean Absolute Error: 123.56330483835745
TRAIN : Mean Squared Error: 62583.65833046191
TRAIN : R2 Score: 0.9960829765842683
TRAIN : Root Mean Squared Error: 250.16726070863453
----------------------------------------------------------
TEST : Mean Absolute Error: 317.938056590411
TEST : Mean Squared Error: 408651.86198325164
TRAIN : R2 Score: 0.9751935692789871
TEST : Root Mean Squared Error: 639.258838017318


#### Cross validation:

In [28]:
scores_randforest = cross_val_score(randforest, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error')
scores_randforest

array([-712.48429664, -638.99579233, -653.91097492])

## 6. K-NEAREST NEIGHBOR

In [29]:
neiclass = KNeighborsClassifier(n_neighbors=5)
neiclass.fit(X_train, y_train)

KNeighborsClassifier()

In [30]:
y_pred_train_neiclass = neiclass.predict(X_train)
y_pred_test_neiclass = neiclass.predict(X_test)

In [32]:
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train, y_pred_train_neiclass))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train, y_pred_train_neiclass))
print('TRAIN : R2 Score:', r2_score(y_train, y_pred_train_neiclass ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train, y_pred_train_neiclass)))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred_test_neiclass ))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred_test_neiclass ))
print('TRAIN : R2 Score:', r2_score(y_test, y_pred_test_neiclass ))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test_neiclass )))

TRAIN : Mean Absolute Error: 941.4369361018415
TRAIN : Mean Squared Error: 3294719.437924855
TRAIN : R2 Score: 0.7937881304657353
TRAIN : Root Mean Squared Error: 1815.1362036841354
----------------------------------------------------------
TEST : Mean Absolute Error: 1106.6510938079348
TEST : Mean Squared Error: 3800990.6377456435
TRAIN : R2 Score: 0.7692681235591184
TEST : Root Mean Squared Error: 1949.6129456242445


#### Cross validation:

In [34]:
scores_neighclass = cross_val_score(neiclass, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error')
scores_neighclass

/home/ubuntu/.local/lib/python3.8/site-packages/sklearn/model_selection/_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(("The least populated class in y has only %d"


array([-2223.11598538, -2198.37679709, -2264.92035349])

## 7. BAYESIAN RIDGE

In [35]:
bay = BayesianRidge() 
bay.fit(X_train, y_train) 

BayesianRidge()

In [36]:
y_pred_train_bay = bay.predict(X_train)
y_pred_test_bay = bay.predict(X_test)

In [37]:
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train, y_pred_train_bay))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train, y_pred_train_bay))
print('TRAIN : R2 Score:', r2_score(y_train, y_pred_train_bay ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train, y_pred_train_bay)))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred_test_bay  ))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred_test_bay  ))
print('TRAIN : R2 Score:', r2_score(y_test, y_pred_test_bay ))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test_bay  )))

TRAIN : Mean Absolute Error: 804.6815127607628
TRAIN : Mean Squared Error: 1338394.8293905589
TRAIN : R2 Score: 0.9162317444190478
TRAIN : Root Mean Squared Error: 1156.8901544185424
----------------------------------------------------------
TEST : Mean Absolute Error: 808.3348174903447
TEST : Mean Squared Error: 1364615.9850446887
TRAIN : R2 Score: 0.9171635931633534
TEST : Root Mean Squared Error: 1168.167789765104


#### Cross validation:

In [39]:
scores_bay = cross_val_score(bay, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error')
scores_bay

array([-1163.75363882, -1142.96315999, -1168.69861407])

## 8. ELASTIC NET

In [40]:
elnet = ElasticNet(random_state=0)
elnet.fit(X_train, y_train)

ElasticNet(random_state=0)

In [41]:
y_pred_train_elnet = elnet.predict(X_train)
y_pred_test_elnet = elnet.predict(X_test)

In [42]:
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train, y_pred_train_elnet))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train, y_pred_train_elnet))
print('TRAIN : R2 Score:', r2_score(y_train, y_pred_train_elnet ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train, y_pred_train_elnet)))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred_test_elnet))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred_test_elnet))
print('TRAIN : R2 Score:', r2_score(y_test, y_pred_test_elnet ))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test_elnet)))

TRAIN : Mean Absolute Error: 1290.997511461224
TRAIN : Mean Squared Error: 3700083.7387806787
TRAIN : R2 Score: 0.7684169473052721
TRAIN : Root Mean Squared Error: 1923.5601729035354
----------------------------------------------------------
TEST : Mean Absolute Error: 1300.1261951215583
TEST : Mean Squared Error: 3794797.0460735178
TRAIN : R2 Score: 0.7696440937112747
TEST : Root Mean Squared Error: 1948.0238823160043


#### Cross validation:

In [43]:
scores_elnet = cross_val_score(elnet, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error')
scores_elnet

array([-1929.47629761, -1908.32221136, -1936.23582499])

## Modify train_size

In [44]:
X_train2, X_test2, y_train2, y_test2 = train_test_split( X, y, train_size=0.9)

## 1.1 LINEAR REGRESSION

In [45]:
#We will try it with the model with the lower rmse, in this case : linear regression

In [46]:
#Train the model
lr_2 = LinearRegression()
lr_2.fit(X_train2, y_train2)

LinearRegression()

In [47]:
y_pred_train_lr_2 = lr_2.predict(X_train2)
y_pred_test_lr_2 = lr_2.predict(X_test2)

In [48]:
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train2, y_pred_train_lr_2  ))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train2, y_pred_train_lr_2  ))
print('TRAIN : R2 Score:', r2_score(y_train2, y_pred_train_lr_2  ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train2, y_pred_train_lr_2  )))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test2, y_pred_test_lr_2 ))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test2, y_pred_test_lr_2 ))
print('TEST : R2 Score:', r2_score(y_test2, y_pred_test_lr_2))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test2, y_pred_test_lr_2 )))

TRAIN : Mean Absolute Error: 806.8535333128821
TRAIN : Mean Squared Error: 1340470.301914223
TRAIN : R2 Score: 0.9168302347155112
TRAIN : Root Mean Squared Error: 1157.786811945197
----------------------------------------------------------
TEST : Mean Absolute Error: 808.6055529419633
TEST : Mean Squared Error: 1371578.88555703
TEST : R2 Score: 0.9126983287880426
TEST : Root Mean Squared Error: 1171.144263341212


#### Cross validation:

In [49]:
scores_lr_2 = cross_val_score(lr_2, X_train2, y_train2, cv=3, scoring='neg_root_mean_squared_error')
scores_lr_2

array([-1155.36346023, -1179.11009235, -1144.23872068])

# Lets introduce the second dataset

In [50]:
#import the dataset:
dmd_pred = pd.read_csv("../resources/predict.csv",index_col="id")

In [51]:
dmd_pred.head()

carat      cut color clarity  depth  table     x     y     z
id                                                              
0    0.45  Premium     E     SI1   62.8   58.0  4.88  4.84  3.05
1    1.23    Ideal     H     SI1   61.0   56.0  6.96  6.92  4.23
2    0.33    Ideal     I      IF   61.8   55.0  4.46  4.47  2.76
3    0.51  Premium     D     VS2   58.0   60.0  5.29  5.26  3.06
4    0.40  Premium     E     VS2   62.2   59.0  4.71  4.74  2.94

In [52]:
# Same steps as with the dataset above:

In [53]:
dmd_pred = dmd_pred.drop(columns = ['x','y','z'])

In [54]:
#Value that are objcts have to be transformed to values that can be used with linear regression
#We create the dummies for the columns we want the type to change
dmd_cl1_dummy = pd.get_dummies(dmd_pred[['cut','color','clarity']], drop_first=True)
dmd_cl1_dummy.head()

dmd_pred = dmd_pred.drop(columns = ['cut','color','clarity'])

#I now join the dummies to the rest of the table
dmd_pred=dmd_pred.join(dmd_cl1_dummy)
dmd_pred.head()

carat  depth  table  cut_Good  cut_Ideal  cut_Premium  cut_Very Good  \
id                                                                         
0    0.45   62.8   58.0         0          0            1              0   
1    1.23   61.0   56.0         0          1            0              0   
2    0.33   61.8   55.0         0          1            0              0   
3    0.51   58.0   60.0         0          0            1              0   
4    0.40   62.2   59.0         0          0            1              0   

    color_E  color_F  color_G  color_H  color_I  color_J  clarity_IF  \
id                                                                     
0         1        0        0        0        0        0           0   
1         0        0        0        1        0        0           0   
2         0        0        0        0        1        0           1   
3         0        0        0        0        0        0           0   
4         1        0        0        0        0        0           0   

    clarity_SI1  clarity_SI2  clarity_VS1  clarity_VS2  clarity_VVS1  \
id                                                                     
0             1            0            0            0             0   
1             1            0            0            0             0   
2             0            0            0            0             0   
3             0            0            0            1             0   
4             0            0            0            1             0   

    clarity_VVS2  
id                
0              0  
1              0  
2              0  
3              0  
4              0

In [55]:
y_pred_predict_test = lr_2 .predict(dmd_pred)

In [56]:
y_pred_predict_test

array([ 847.96981371, 7181.14156555,  546.14424564, ..., 1358.01350013,
        -88.36475779, 4932.42935124])

In [57]:
dmd_pred['price'] = y_pred_predict_test
dmd_pred.head()

carat  depth  table  cut_Good  cut_Ideal  cut_Premium  cut_Very Good  \
id                                                                         
0    0.45   62.8   58.0         0          0            1              0   
1    1.23   61.0   56.0         0          1            0              0   
2    0.33   61.8   55.0         0          1            0              0   
3    0.51   58.0   60.0         0          0            1              0   
4    0.40   62.2   59.0         0          0            1              0   

    color_E  color_F  color_G  ...  color_I  color_J  clarity_IF  clarity_SI1  \
id                             ...                                              
0         1        0        0  ...        0        0           0            1   
1         0        0        0  ...        0        0           0            1   
2         0        0        0  ...        1        0           1            0   
3         0        0        0  ...        0        0           0            0   
4         1        0        0  ...        0        0           0            0   

    clarity_SI2  clarity_VS1  clarity_VS2  clarity_VVS1  clarity_VVS2  \
id                                                                      
0             0            0            0             0             0   
1             0            0            0             0             0   
2             0            0            0             0             0   
3             0            0            1             0             0   
4             0            0            1             0             0   

          price  
id               
0    847.969814  
1   7181.141566  
2    546.144246  
3   2292.622981  
4   1038.073633  

[5 rows x 21 columns]

In [58]:
#export

In [59]:
dmd_pred["price"].to_csv("final1.csv",header= True )