In [1]:
#import the libraries:
import pandas as pd 
import numpy as np
from sklearn import metrics
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import BayesianRidge 
from sklearn.linear_model import ElasticNet

# Models:

In [2]:
# import the clean datasets
#%store -r dmd_cl1
#%store -r dmd_cl2
%store -r dmd_cl3
#%store -r dmd_cl4

In [3]:
X = dmd_cl3.drop(columns = 'price')
y = dmd_cl3['price']

#### Lets divide the dataset into train and test

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train, X_test, y_train, y_test = train_test_split( X, y, train_size=0.8)

In [6]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

## 1. LINEAR REGRESSION

In [7]:
#Train the model
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [8]:
y_pred_train_lr = lr.predict(X_train)
y_pred_test_lr = lr.predict(X_test)

In [9]:
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train, y_pred_train_lr ))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train, y_pred_train_lr ))
print('TRAIN : R2 Score:', r2_score(y_train, y_pred_train_lr ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train, y_pred_train_lr )))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred_test_lr ))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred_test_lr ))
print('TEST : R2 Score:', r2_score(y_test, y_pred_test_lr))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test_lr )))

TRAIN : Mean Absolute Error: 842.1100780123819
TRAIN : Mean Squared Error: 1484029.7022468033
TRAIN : R2 Score: 0.9077240378703295
TRAIN : Root Mean Squared Error: 1218.2075776511995
----------------------------------------------------------
TEST : Mean Absolute Error: 841.6332932846606
TEST : Mean Squared Error: 1474225.5698174324
TEST : R2 Score: 0.9081720720199449
TEST : Root Mean Squared Error: 1214.1769104283908


#### Cross Validation:

In [10]:
scores_lr = cross_val_score(lr, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error')
scores_lr

array([-1201.00103824, -1233.97529791, -1220.05287217])

## 2. LASSO

In [11]:
lasso = Lasso()
lasso.fit(X_train, y_train)

Lasso()

In [12]:
y_pred_train_lasso = lasso.predict(X_train)
y_pred_test_lasso = lasso.predict(X_test)

In [13]:
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train, y_pred_train_lasso ))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train, y_pred_train_lasso ))
print('TRAIN : R2 Score:', r2_score(y_train, y_pred_train_lasso ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train, y_pred_train_lasso )))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred_test_lasso ))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred_test_lasso ))
print('TEST : R2 Score:', r2_score(y_test, y_pred_test_lasso))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test_lasso )))

TRAIN : Mean Absolute Error: 841.7000071382431
TRAIN : Mean Squared Error: 1484037.861129996
TRAIN : R2 Score: 0.9077235305564966
TRAIN : Root Mean Squared Error: 1218.2109263711257
----------------------------------------------------------
TEST : Mean Absolute Error: 841.2688758011561
TEST : Mean Squared Error: 1474464.657495942
TEST : R2 Score: 0.9081571795051409
TEST : Root Mean Squared Error: 1214.2753631264789


#### Cross Validation:

In [14]:
scores_lasso = cross_val_score(lasso, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error')
scores_lasso

array([-1200.98819386, -1233.97373848, -1220.07743885])

## 3. RIDGE

In [15]:
ridge = Ridge(alpha = 1)
ridge.fit(X_train, y_train)

Ridge(alpha=1)

In [16]:
y_pred_train_ridge = ridge.predict(X_train)
y_pred_test_ridge = ridge.predict(X_test)

In [17]:
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train, y_pred_train_ridge ))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train, y_pred_train_ridge ))
print('TRAIN : R2 Score:', r2_score(y_train, y_pred_train_ridge ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train, y_pred_train_ridge )))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred_test_ridge ))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred_test_ridge ))
print('TEST : R2 Score:', r2_score(y_test, y_pred_test_ridge))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test_ridge )))

TRAIN : Mean Absolute Error: 842.085565527034
TRAIN : Mean Squared Error: 1484029.730843484
TRAIN : R2 Score: 0.9077240360922073
TRAIN : Root Mean Squared Error: 1218.2075893883948
----------------------------------------------------------
TEST : Mean Absolute Error: 841.6107961899102
TEST : Mean Squared Error: 1474238.9898835714
TEST : R2 Score: 0.9081712360984332
TEST : Root Mean Squared Error: 1214.182436820584


#### Cross validation : 

In [18]:
scores_ridge = cross_val_score(lasso, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error')
scores_ridge

array([-1200.98819386, -1233.97373848, -1220.07743885])

## 4. DECISSION TREE

In [19]:
tree = DecisionTreeClassifier(max_depth = 3)
tree.fit(X_train, y_train)
y_pred_train_tree = tree.predict(X_train)
y_pred_test_tree = tree.predict(X_test)

In [20]:
from sklearn import metrics
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train, y_pred_train_tree))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train, y_pred_train_tree))
print('TRAIN : R2 Score:', r2_score(y_train, y_pred_train_tree ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train, y_pred_train_tree)))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred_test_tree ))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred_test_tree ))
print('TRAIN : R2 Score:', r2_score(y_test, y_pred_test_tree ))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test_tree )))

TRAIN : Mean Absolute Error: 3374.6317513286367
TRAIN : Mean Squared Error: 27382720.430540107
TRAIN : R2 Score: -0.7026390170158847
TRAIN : Root Mean Squared Error: 5232.850124983526
----------------------------------------------------------
TEST : Mean Absolute Error: 3365.1307625757013
TEST : Mean Squared Error: 27299616.828451365
TRAIN : R2 Score: -0.7004638227219064
TEST : Root Mean Squared Error: 5224.903523363027


#### Cross validation:

In [21]:
scores_tree = cross_val_score(tree, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error')
scores_tree

/home/ubuntu/.local/lib/python3.8/site-packages/sklearn/model_selection/_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(("The least populated class in y has only %d"


array([-5093.87257882, -5248.97289501, -5209.97976869])

## 5. RANDOM FOREST

In [22]:
randforest = RandomForestRegressor(n_estimators=20, random_state=10)
randforest.fit(X_train, y_train)
y_pred_train_randforest = randforest.predict(X_train)
y_pred_test_randforest = randforest.predict(X_test)

In [23]:
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train, y_pred_train_randforest))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train, y_pred_train_randforest))
print('TRAIN : R2 Score:', r2_score(y_train, y_pred_train_randforest ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train, y_pred_train_randforest)))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred_test_randforest ))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred_test_randforest ))
print('TRAIN : R2 Score:', r2_score(y_test, y_pred_test_randforest ))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test_randforest )))

TRAIN : Mean Absolute Error: 116.90491024001697
TRAIN : Mean Squared Error: 50896.36397063746
TRAIN : R2 Score: 0.9968352985474738
TRAIN : Root Mean Squared Error: 225.60222510125527
----------------------------------------------------------
TEST : Mean Absolute Error: 290.66863726227973
TEST : Mean Squared Error: 322648.8926861581
TRAIN : R2 Score: 0.9799025468781564
TEST : Root Mean Squared Error: 568.0219121531828


#### Cross validation:

In [24]:
scores_randforest = cross_val_score(randforest, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error')
scores_randforest

array([-588.57501736, -582.24556724, -604.63494307])

## 6. K-NEAREST NEIGHBOR

In [25]:
neiclass = KNeighborsClassifier(n_neighbors=5)
neiclass.fit(X_train, y_train)

KNeighborsClassifier()

In [26]:
y_pred_train_neiclass = neiclass.predict(X_train)
y_pred_test_neiclass = neiclass.predict(X_test)

In [27]:
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train, y_pred_train_neiclass))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train, y_pred_train_neiclass))
print('TRAIN : R2 Score:', r2_score(y_train, y_pred_train_neiclass ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train, y_pred_train_neiclass)))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred_test_neiclass ))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred_test_neiclass ))
print('TRAIN : R2 Score:', r2_score(y_test, y_pred_test_neiclass ))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test_neiclass )))

TRAIN : Mean Absolute Error: 787.25241008528
TRAIN : Mean Squared Error: 1969540.2887467556
TRAIN : R2 Score: 0.8775353183146524
TRAIN : Root Mean Squared Error: 1403.4031098536
----------------------------------------------------------
TEST : Mean Absolute Error: 942.9902360647633
TEST : Mean Squared Error: 2534400.663700408
TRAIN : R2 Score: 0.8421349036513416
TEST : Root Mean Squared Error: 1591.9801078218306


#### Cross validation:

In [28]:
scores_neighclass = cross_val_score(neiclass, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error')
scores_neighclass

/home/ubuntu/.local/lib/python3.8/site-packages/sklearn/model_selection/_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(("The least populated class in y has only %d"


array([-1670.24937176, -1666.80614657, -1657.26052875])

## 7. BAYESIAN RIDGE

In [29]:
bay = BayesianRidge() 
bay.fit(X_train, y_train) 

BayesianRidge()

In [30]:
y_pred_train_bay = bay.predict(X_train)
y_pred_test_bay = bay.predict(X_test)

In [31]:
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train, y_pred_train_bay))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train, y_pred_train_bay))
print('TRAIN : R2 Score:', r2_score(y_train, y_pred_train_bay ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train, y_pred_train_bay)))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred_test_bay  ))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred_test_bay  ))
print('TRAIN : R2 Score:', r2_score(y_test, y_pred_test_bay ))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test_bay  )))

TRAIN : Mean Absolute Error: 842.0985057739433
TRAIN : Mean Squared Error: 1484029.708619339
TRAIN : R2 Score: 0.9077240374740896
TRAIN : Root Mean Squared Error: 1218.2075802667373
----------------------------------------------------------
TEST : Mean Absolute Error: 841.6226601001989
TEST : Mean Squared Error: 1474231.897938157
TRAIN : R2 Score: 0.908171677848099
TEST : Root Mean Squared Error: 1214.179516355863


#### Cross validation:

In [32]:
scores_bay = cross_val_score(bay, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error')
scores_bay

array([-1201.00133415, -1233.97296348, -1220.05493529])

## 8. ELASTIC NET

In [33]:
elnet = ElasticNet(random_state=0)
elnet.fit(X_train, y_train)

ElasticNet(random_state=0)

In [34]:
y_pred_train_elnet = elnet.predict(X_train)
y_pred_test_elnet = elnet.predict(X_test)

In [35]:
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train, y_pred_train_elnet))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train, y_pred_train_elnet))
print('TRAIN : R2 Score:', r2_score(y_train, y_pred_train_elnet ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train, y_pred_train_elnet)))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred_test_elnet))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred_test_elnet))
print('TRAIN : R2 Score:', r2_score(y_test, y_pred_test_elnet ))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test_elnet)))

TRAIN : Mean Absolute Error: 1298.3796655145761
TRAIN : Mean Squared Error: 3693633.6577428957
TRAIN : R2 Score: 0.7703323599205988
TRAIN : Root Mean Squared Error: 1921.8828418358116
----------------------------------------------------------
TEST : Mean Absolute Error: 1301.8316985028355
TEST : Mean Squared Error: 3752067.4847432696
TRAIN : R2 Score: 0.7662877446848384
TEST : Root Mean Squared Error: 1937.0254218113064


#### Cross validation:

In [36]:
scores_elnet = cross_val_score(elnet, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error')
scores_elnet

array([-1915.35264641, -1925.44001665, -1925.78220258])

## Modify train_size

In [37]:
X_train2, X_test2, y_train2, y_test2 = train_test_split( X, y, train_size=0.9)

## 1.1 LINEAR REGRESSION

In [38]:
#We will try it with the model with the lower rmse, in this case : linear regression

In [39]:
#Train the model
lr_2 = LinearRegression()
lr_2.fit(X_train2, y_train2)

LinearRegression()

In [40]:
y_pred_train_lr_2 = lr_2.predict(X_train2)
y_pred_test_lr_2 = lr_2.predict(X_test2)

In [41]:
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train2, y_pred_train_lr_2  ))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train2, y_pred_train_lr_2  ))
print('TRAIN : R2 Score:', r2_score(y_train2, y_pred_train_lr_2  ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train2, y_pred_train_lr_2  )))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test2, y_pred_test_lr_2 ))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test2, y_pred_test_lr_2 ))
print('TEST : R2 Score:', r2_score(y_test2, y_pred_test_lr_2))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test2, y_pred_test_lr_2 )))

TRAIN : Mean Absolute Error: 845.0206825458262
TRAIN : Mean Squared Error: 1490385.7066061005
TRAIN : R2 Score: 0.9073620352701804
TRAIN : Root Mean Squared Error: 1220.8135429319666
----------------------------------------------------------
TEST : Mean Absolute Error: 833.8776141297295
TEST : Mean Squared Error: 1407027.2133545561
TEST : R2 Score: 0.9118823671172167
TEST : Root Mean Squared Error: 1186.1817792204347


#### Cross validation:

In [42]:
scores_lr_2 = cross_val_score(lr_2, X_train2, y_train2, cv=3, scoring='neg_root_mean_squared_error')
scores_lr_2

array([-1242.10098954, -1205.87155308, -1215.75511393])

# Lets introduce the second dataset

In [43]:
#import the dataset:
dmd_pred = pd.read_csv("../datasets/predict.csv",index_col="id")

In [44]:
dmd_pred.head()

carat      cut color clarity  depth  table     x     y     z
id                                                              
0    0.45  Premium     E     SI1   62.8   58.0  4.88  4.84  3.05
1    1.23    Ideal     H     SI1   61.0   56.0  6.96  6.92  4.23
2    0.33    Ideal     I      IF   61.8   55.0  4.46  4.47  2.76
3    0.51  Premium     D     VS2   58.0   60.0  5.29  5.26  3.06
4    0.40  Premium     E     VS2   62.2   59.0  4.71  4.74  2.94

In [45]:
# Same steps as with the dataset above:

In [46]:
dmd_pred = dmd_pred.drop(columns = ['x','y','z'])

In [47]:
dmd_pred["cut"].replace({"Ideal": 5, "Premium": 4, "Very Good" : 3, "Good" : 2, "Fair" : 1}, inplace=True)
dmd_pred["color"].replace({"D": 7, "E": 6, "F" : 5, "G" : 4, "H" : 3, "I": 2 , "J": 1}, inplace=True)
dmd_pred["clarity"].replace({"IF": 9, "VVS1": 8, "VVS2" : 7, 
                             "VS1" : 6, "VS2" : 5, "SI1": 4, 
                             "SI2" : 2, "I1": 1 }, inplace=True)

In [48]:
dmd_pred.head()

carat  cut  color  clarity  depth  table
id                                          
0    0.45    4      6        4   62.8   58.0
1    1.23    5      3        4   61.0   56.0
2    0.33    5      2        9   61.8   55.0
3    0.51    4      7        5   58.0   60.0
4    0.40    4      6        5   62.2   59.0

In [49]:
y_pred_predict_test = lr_2 .predict(dmd_pred)

In [50]:
y_pred_predict_test

array([ 910.86071512, 7108.06329269, 1154.63438085, ..., 1657.03343698,
       -478.89860963, 4905.52845835])

In [51]:
dmd_pred['price'] = y_pred_predict_test
dmd_pred.head()

carat  cut  color  clarity  depth  table        price
id                                                       
0    0.45    4      6        4   62.8   58.0   910.860715
1    1.23    5      3        4   61.0   56.0  7108.063293
2    0.33    5      2        9   61.8   55.0  1154.634381
3    0.51    4      7        5   58.0   60.0  2392.390557
4    0.40    4      6        5   62.2   59.0   938.482501

In [55]:
#export

In [56]:
dmd_pred["price"].to_csv("final3.csv",header= True )