In [1]:
#import the libraries:
import pandas as pd 
import numpy as np
from sklearn import metrics
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import BayesianRidge 
from sklearn.linear_model import ElasticNet

# Models:

In [2]:
# import the clean datasets
#%store -r dmd_cl1
#%store -r dmd_cl2
#%store -r dmd_cl3
%store -r dmd_cl4

In [3]:
X = dmd_cl4.drop(columns = 'price')
y = dmd_cl4['price']

#### Lets divide the dataset into train and test

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train, X_test, y_train, y_test = train_test_split( X, y, train_size=0.8)

In [6]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

## 1. LINEAR REGRESSION

In [7]:
#Train the model
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [8]:
y_pred_train_lr = lr.predict(X_train)
y_pred_test_lr = lr.predict(X_test)

In [9]:
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train, y_pred_train_lr ))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train, y_pred_train_lr ))
print('TRAIN : R2 Score:', r2_score(y_train, y_pred_train_lr ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train, y_pred_train_lr )))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred_test_lr ))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred_test_lr ))
print('TEST : R2 Score:', r2_score(y_test, y_pred_test_lr))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test_lr )))

TRAIN : Mean Absolute Error: 864.6818404050429
TRAIN : Mean Squared Error: 2003557.9341667676
TRAIN : R2 Score: 0.8754658968370663
TRAIN : Root Mean Squared Error: 1415.470923108902
----------------------------------------------------------
TEST : Mean Absolute Error: 885.9179206030142
TEST : Mean Squared Error: 6261286.3810059335
TEST : R2 Score: 0.6094074539305858
TEST : Root Mean Squared Error: 2502.256258061099


#### Cross Validation:

In [10]:
scores_lr = cross_val_score(lr, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error')
scores_lr

array([-1466.68187921, -1386.16949887, -1394.65881442])

## 2. LASSO

In [11]:
lasso = Lasso()
lasso.fit(X_train, y_train)

/home/ubuntu/.local/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 2795654729.7638397, tolerance: 52068587.90843517
  model = cd_fast.enet_coordinate_descent(


Lasso()

In [12]:
y_pred_train_lasso = lasso.predict(X_train)
y_pred_test_lasso = lasso.predict(X_test)

In [13]:
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train, y_pred_train_lasso ))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train, y_pred_train_lasso ))
print('TRAIN : R2 Score:', r2_score(y_train, y_pred_train_lasso ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train, y_pred_train_lasso )))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred_test_lasso ))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred_test_lasso ))
print('TEST : R2 Score:', r2_score(y_test, y_pred_test_lasso))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test_lasso )))

TRAIN : Mean Absolute Error: 863.0642106619738
TRAIN : Mean Squared Error: 2005838.997334358
TRAIN : R2 Score: 0.8753241139861742
TRAIN : Root Mean Squared Error: 1416.2764551225011
----------------------------------------------------------
TEST : Mean Absolute Error: 877.4804152389229
TEST : Mean Squared Error: 4397261.392724095
TEST : R2 Score: 0.72568935221888
TEST : Root Mean Squared Error: 2096.964804836766


#### Cross Validation:

In [14]:
scores_lasso = cross_val_score(lasso, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error')
scores_lasso

/home/ubuntu/.local/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1099534250.6013527, tolerance: 34564516.70170212
  model = cd_fast.enet_coordinate_descent(
/home/ubuntu/.local/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 2848918044.374222, tolerance: 34809844.87011657
  model = cd_fast.enet_coordinate_descent(
/home/ubuntu/.local/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1924499270.0990295, tolerance: 34762207.46673121
  model = cd_fast.enet_coordinate_descent(


array([-1468.47894812, -1385.39350237, -1395.62148821])

## 3. RIDGE

In [15]:
ridge = Ridge(alpha = 1)
ridge.fit(X_train, y_train)

Ridge(alpha=1)

In [16]:
y_pred_train_ridge = ridge.predict(X_train)
y_pred_test_ridge = ridge.predict(X_test)

In [17]:
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train, y_pred_train_ridge ))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train, y_pred_train_ridge ))
print('TRAIN : R2 Score:', r2_score(y_train, y_pred_train_ridge ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train, y_pred_train_ridge )))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred_test_ridge ))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred_test_ridge ))
print('TEST : R2 Score:', r2_score(y_test, y_pred_test_ridge))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test_ridge )))

TRAIN : Mean Absolute Error: 864.4988485843639
TRAIN : Mean Squared Error: 2003569.6189445136
TRAIN : R2 Score: 0.8754651705524442
TRAIN : Root Mean Squared Error: 1415.4750506259422
----------------------------------------------------------
TEST : Mean Absolute Error: 885.2486487666647
TEST : Mean Squared Error: 6110042.461659178
TEST : R2 Score: 0.6188423757566142
TEST : Root Mean Squared Error: 2471.850007921026


#### Cross validation : 

In [18]:
scores_ridge = cross_val_score(lasso, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error')
scores_ridge

/home/ubuntu/.local/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1099534250.6013527, tolerance: 34564516.70170212
  model = cd_fast.enet_coordinate_descent(
/home/ubuntu/.local/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 2848918044.374222, tolerance: 34809844.87011657
  model = cd_fast.enet_coordinate_descent(
/home/ubuntu/.local/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1924499270.0990295, tolerance: 34762207.46673121
  model = cd_fast.enet_coordinate_descent(


array([-1468.47894812, -1385.39350237, -1395.62148821])

## 4. DECISSION TREE

In [19]:
tree = DecisionTreeClassifier(max_depth = 3)
tree.fit(X_train, y_train)
y_pred_train_tree = tree.predict(X_train)
y_pred_test_tree = tree.predict(X_test)

In [20]:
from sklearn import metrics
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train, y_pred_train_tree))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train, y_pred_train_tree))
print('TRAIN : R2 Score:', r2_score(y_train, y_pred_train_tree ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train, y_pred_train_tree)))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred_test_tree ))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred_test_tree ))
print('TRAIN : R2 Score:', r2_score(y_test, y_pred_test_tree ))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test_tree )))

TRAIN : Mean Absolute Error: 3200.924916573971
TRAIN : Mean Squared Error: 25903675.46446669
TRAIN : R2 Score: -0.6100812148127972
TRAIN : Root Mean Squared Error: 5089.565351232529
----------------------------------------------------------
TEST : Mean Absolute Error: 3178.623161537511
TEST : Mean Squared Error: 25706377.68508219
TRAIN : R2 Score: -0.6036192723427372
TEST : Root Mean Squared Error: 5070.14572621756


#### Cross validation:

In [21]:
scores_tree = cross_val_score(tree, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error')
scores_tree

/home/ubuntu/.local/lib/python3.8/site-packages/sklearn/model_selection/_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(("The least populated class in y has only %d"


array([-5127.8648377 , -5081.51354705, -5059.21479404])

## 5. RANDOM FOREST

In [22]:
randforest = RandomForestRegressor(n_estimators=20, random_state=10)
randforest.fit(X_train, y_train)
y_pred_train_randforest = randforest.predict(X_train)
y_pred_test_randforest = randforest.predict(X_test)

In [23]:
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train, y_pred_train_randforest))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train, y_pred_train_randforest))
print('TRAIN : R2 Score:', r2_score(y_train, y_pred_train_randforest ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train, y_pred_train_randforest)))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred_test_randforest ))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred_test_randforest ))
print('TRAIN : R2 Score:', r2_score(y_test, y_pred_test_randforest ))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test_randforest )))

TRAIN : Mean Absolute Error: 111.29563139857042
TRAIN : Mean Squared Error: 54097.99670721143
TRAIN : R2 Score: 0.9966374590981589
TRAIN : Root Mean Squared Error: 232.58976053818756
----------------------------------------------------------
TEST : Mean Absolute Error: 289.630578994297
TEST : Mean Squared Error: 357539.7362202112
TRAIN : R2 Score: 0.9776959002682125
TEST : Root Mean Squared Error: 597.9462653284249


#### Cross validation:

In [24]:
scores_randforest = cross_val_score(randforest, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error')
scores_randforest

array([-599.09066355, -571.42743891, -587.47221605])

## 6. K-NEAREST NEIGHBOR

In [25]:
neiclass = KNeighborsClassifier(n_neighbors=5)
neiclass.fit(X_train, y_train)

KNeighborsClassifier()

In [26]:
y_pred_train_neiclass = neiclass.predict(X_train)
y_pred_test_neiclass = neiclass.predict(X_test)

In [27]:
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train, y_pred_train_neiclass))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train, y_pred_train_neiclass))
print('TRAIN : R2 Score:', r2_score(y_train, y_pred_train_neiclass ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train, y_pred_train_neiclass)))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred_test_neiclass ))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred_test_neiclass ))
print('TRAIN : R2 Score:', r2_score(y_test, y_pred_test_neiclass ))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test_neiclass )))

TRAIN : Mean Absolute Error: 438.6840316400939
TRAIN : Mean Squared Error: 1015354.9826968237
TRAIN : R2 Score: 0.9368891111128509
TRAIN : Root Mean Squared Error: 1007.6482435338354
----------------------------------------------------------
TEST : Mean Absolute Error: 544.7096774193549
TEST : Mean Squared Error: 1299536.1369422816
TRAIN : R2 Score: 0.9189321335025811
TEST : Root Mean Squared Error: 1139.971989542849


#### Cross validation:

In [28]:
scores_neighclass = cross_val_score(neiclass, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error')
scores_neighclass

/home/ubuntu/.local/lib/python3.8/site-packages/sklearn/model_selection/_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(("The least populated class in y has only %d"


array([-1179.47789883, -1219.72107285, -1188.79230839])

## 7. BAYESIAN RIDGE

In [29]:
bay = BayesianRidge() 
bay.fit(X_train, y_train) 

BayesianRidge()

In [30]:
y_pred_train_bay = bay.predict(X_train)
y_pred_test_bay = bay.predict(X_test)

In [31]:
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train, y_pred_train_bay))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train, y_pred_train_bay))
print('TRAIN : R2 Score:', r2_score(y_train, y_pred_train_bay ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train, y_pred_train_bay)))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred_test_bay  ))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred_test_bay  ))
print('TRAIN : R2 Score:', r2_score(y_test, y_pred_test_bay ))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test_bay  )))

TRAIN : Mean Absolute Error: 864.5914191513535
TRAIN : Mean Squared Error: 2003560.6779282603
TRAIN : R2 Score: 0.8754657262945176
TRAIN : Root Mean Squared Error: 1415.4718923130406
----------------------------------------------------------
TEST : Mean Absolute Error: 885.5918781081949
TEST : Mean Squared Error: 6187639.15189927
TRAIN : R2 Score: 0.6140017268926075
TEST : Root Mean Squared Error: 2487.4965631934588


#### Cross validation:

In [32]:
scores_bay = cross_val_score(bay, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error')
scores_bay

array([-1466.75000451, -1386.0721248 , -1394.66457946])

## 8. ELASTIC NET

In [33]:
elnet = ElasticNet(random_state=0)
elnet.fit(X_train, y_train)

ElasticNet(random_state=0)

In [34]:
y_pred_train_elnet = elnet.predict(X_train)
y_pred_test_elnet = elnet.predict(X_test)

In [35]:
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train, y_pred_train_elnet))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train, y_pred_train_elnet))
print('TRAIN : R2 Score:', r2_score(y_train, y_pred_train_elnet ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train, y_pred_train_elnet)))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred_test_elnet))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred_test_elnet))
print('TRAIN : R2 Score:', r2_score(y_test, y_pred_test_elnet ))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test_elnet)))

TRAIN : Mean Absolute Error: 1132.285015094545
TRAIN : Mean Squared Error: 3016552.618241322
TRAIN : R2 Score: 0.8125017157975459
TRAIN : Root Mean Squared Error: 1736.8225638335432
----------------------------------------------------------
TEST : Mean Absolute Error: 1134.3774979527443
TEST : Mean Squared Error: 3188559.7014862564
TRAIN : R2 Score: 0.8010907701209862
TEST : Root Mean Squared Error: 1785.6538582508808


#### Cross validation:

In [36]:
scores_elnet = cross_val_score(elnet, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error')
scores_elnet

array([-1773.72093258, -1709.2798257 , -1727.4172605 ])

## Modify train_size

In [37]:
X_train2, X_test2, y_train2, y_test2 = train_test_split( X, y, train_size=0.9)

## 6.1 K-NEAREST NEIGHBOR

In [38]:
#We will try it with the model with the lower rmse, in this case : k-nearest neighbor

In [39]:
#Train the model
neiclass_2 = KNeighborsClassifier(n_neighbors=5)
neiclass_2.fit(X_train2, y_train2)

KNeighborsClassifier()

In [40]:
y_pred_train_neiclass_2 = neiclass_2.predict(X_train2)
y_pred_test_neiclass_2 = neiclass_2.predict(X_test2)

In [41]:
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train2, y_pred_train_neiclass_2))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train2, y_pred_train_neiclass_2))
print('TRAIN : R2 Score:', r2_score(y_train2, y_pred_train_neiclass_2 ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train2, y_pred_train_neiclass_2)))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test2, y_pred_test_neiclass_2 ))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test2, y_pred_test_neiclass_2 ))
print('TRAIN : R2 Score:', r2_score(y_test2, y_pred_test_neiclass_2 ))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test2, y_pred_test_neiclass_2 )))

TRAIN : Mean Absolute Error: 412.6754373918537
TRAIN : Mean Squared Error: 888587.9903320607
TRAIN : R2 Score: 0.9447617175904269
TRAIN : Root Mean Squared Error: 942.6494525177749
----------------------------------------------------------
TEST : Mean Absolute Error: 503.5556104794859
TEST : Mean Squared Error: 1056702.574888779
TRAIN : R2 Score: 0.9339028009515552
TEST : Root Mean Squared Error: 1027.9603955837886


#### Cross validation:

In [42]:
scores_neighclass_2 = cross_val_score(neiclass_2, X_train2, y_train2, cv=3, scoring='neg_root_mean_squared_error')
scores_neighclass_2

/home/ubuntu/.local/lib/python3.8/site-packages/sklearn/model_selection/_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(("The least populated class in y has only %d"


array([-1139.12688107, -1097.47606436, -1134.22437631])

# Lets introduce the second dataset

In [43]:
#import the dataset:
dmd_pred = pd.read_csv("../datasets/predict.csv",index_col="id")

In [44]:
# Same steps as with the dataset above:

In [45]:
drop1_lc = dmd_pred.drop(columns=['depth'])
drop1_lc.head()

carat      cut color clarity  table     x     y     z
id                                                       
0    0.45  Premium     E     SI1   58.0  4.88  4.84  3.05
1    1.23    Ideal     H     SI1   56.0  6.96  6.92  4.23
2    0.33    Ideal     I      IF   55.0  4.46  4.47  2.76
3    0.51  Premium     D     VS2   60.0  5.29  5.26  3.06
4    0.40  Premium     E     VS2   59.0  4.71  4.74  2.94

In [46]:
drop1_lc['cut_weight']=drop1_lc['cut']/drop1_lc['carat']
drop1_lc['color_weight']=drop1_lc['color']/drop1_lc['carat']
drop1_lc['clarity_weight']=drop1_lc['clarity']/drop1_lc['carat']
dmd_cl4 = drop1_lc.drop(['cut','color','clarity','depth','table'], axis=1)

TypeError: unsupported operand type(s) for /: 'str' and 'float'

In [55]:
y_pred_predict_test = neiclass_2 .predict(dmd_pred)

In [48]:
y_pred_predict_test

In [47]:
dmd_pred['price'] = y_pred_predict_test
dmd_pred.head()

In [58]:
#export

In [59]:
dmd_pred["price"].to_csv("final4.csv",header= True )