In [2]:
#import the libraries:
import pandas as pd 
import numpy as np
from sklearn import metrics
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import BayesianRidge 
from sklearn.linear_model import ElasticNet

# Models:

In [3]:
# import the clean datasets
%store -r dmd_cl1
#%store -r dmd_cl2
#%store -r dmd_cl3
#%store -r dmd_cl4

In [4]:
# LETS START WITH CL1

In [5]:
X = dmd_cl1.drop(columns = 'price')
y = dmd_cl1['price']

#### Lets divide the dataset into train and test

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split( X, y, train_size=0.8)

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

## 1. LINEAR REGRESSION

In [9]:
#Train the model
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [10]:
y_pred_train_lr = lr.predict(X_train)
y_pred_test_lr = lr.predict(X_test)

In [11]:
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train, y_pred_train_lr ))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train, y_pred_train_lr ))
print('TRAIN : R2 Score:', r2_score(y_train, y_pred_train_lr ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train, y_pred_train_lr )))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred_test_lr ))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred_test_lr ))
print('TEST : R2 Score:', r2_score(y_test, y_pred_test_lr))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test_lr )))

TRAIN : Mean Absolute Error: 806.1879220016751
TRAIN : Mean Squared Error: 1337814.5591616044
TRAIN : R2 Score: 0.916554730639912
TRAIN : Root Mean Squared Error: 1156.6393384117646
----------------------------------------------------------
TEST : Mean Absolute Error: 809.3139434876372
TEST : Mean Squared Error: 1367087.403667123
TEST : R2 Score: 0.9158981011215271
TEST : Root Mean Squared Error: 1169.225129591014


#### Cross Validation:

In [12]:
scores_lr = cross_val_score(lr, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error')
scores_lr

array([-1183.1677089 , -1155.16744418, -1134.35961962])

## 2. LASSO

In [13]:
lasso = Lasso()
lasso.fit(X_train, y_train)

Lasso()

In [14]:
y_pred_train_lasso = lasso.predict(X_train)
y_pred_test_lasso = lasso.predict(X_test)

In [15]:
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train, y_pred_train_lasso ))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train, y_pred_train_lasso ))
print('TRAIN : R2 Score:', r2_score(y_train, y_pred_train_lasso ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train, y_pred_train_lasso )))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred_test_lasso ))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred_test_lasso ))
print('TEST : R2 Score:', r2_score(y_test, y_pred_test_lasso))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test_lasso )))

TRAIN : Mean Absolute Error: 804.2767471575091
TRAIN : Mean Squared Error: 1338316.6538149533
TRAIN : R2 Score: 0.9165234128288551
TRAIN : Root Mean Squared Error: 1156.8563669768832
----------------------------------------------------------
TEST : Mean Absolute Error: 807.373898983919
TEST : Mean Squared Error: 1367249.6970729495
TEST : R2 Score: 0.9158881169876898
TEST : Root Mean Squared Error: 1169.2945296515115


#### Cross Validation:

In [16]:
scores_lasso = cross_val_score(lasso, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error')
scores_lasso

array([-1184.00468963, -1155.80737166, -1133.60652151])

## 3. RIDGE

In [17]:
ridge = Ridge(alpha = 1)
ridge.fit(X_train, y_train)

Ridge(alpha=1)

In [18]:
y_pred_train_ridge = ridge.predict(X_train)
y_pred_test_ridge = ridge.predict(X_test)

In [19]:
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train, y_pred_train_ridge ))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train, y_pred_train_ridge ))
print('TRAIN : R2 Score:', r2_score(y_train, y_pred_train_ridge ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train, y_pred_train_ridge )))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred_test_ridge ))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred_test_ridge ))
print('TEST : R2 Score:', r2_score(y_test, y_pred_test_ridge))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test_ridge )))

TRAIN : Mean Absolute Error: 806.1090656518691
TRAIN : Mean Squared Error: 1337815.3576744455
TRAIN : R2 Score: 0.9165546808332189
TRAIN : Root Mean Squared Error: 1156.6396835983303
----------------------------------------------------------
TEST : Mean Absolute Error: 809.2372381938995
TEST : Mean Squared Error: 1367082.472240134
TEST : R2 Score: 0.9158984044981604
TEST : Root Mean Squared Error: 1169.2230207450305


#### Cross validation : 

In [20]:
scores_ridge = cross_val_score(lasso, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error')
scores_ridge

array([-1184.00468963, -1155.80737166, -1133.60652151])

## 4. DECISSION TREE

In [21]:
tree = DecisionTreeClassifier(max_depth = 3)
tree.fit(X_train, y_train)
y_pred_train_tree = tree.predict(X_train)
y_pred_test_tree = tree.predict(X_test)

In [22]:
from sklearn import metrics
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train, y_pred_train_tree))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train, y_pred_train_tree))
print('TRAIN : R2 Score:', r2_score(y_train, y_pred_train_tree ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train, y_pred_train_tree)))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred_test_tree ))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred_test_tree ))
print('TRAIN : R2 Score:', r2_score(y_test, y_pred_test_tree ))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test_tree )))

TRAIN : Mean Absolute Error: 3200.3842541095046
TRAIN : Mean Squared Error: 25842209.302620195
TRAIN : R2 Score: -0.6118901542440351
TRAIN : Root Mean Squared Error: 5083.523315833241
----------------------------------------------------------
TEST : Mean Absolute Error: 3183.6362625139045
TEST : Mean Squared Error: 25954946.24014337
TRAIN : R2 Score: -0.5967232659955441
TEST : Root Mean Squared Error: 5094.599713436118


#### Cross validation:

In [23]:
scores_tree = cross_val_score(tree, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error')
scores_tree

/home/ubuntu/.local/lib/python3.8/site-packages/sklearn/model_selection/_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(("The least populated class in y has only %d"


array([-5048.76172414, -5097.5876312 , -5103.91596997])

## 5. RANDOM FOREST

In [24]:
randforest = RandomForestRegressor(n_estimators=20, random_state=10)
randforest.fit(X_train, y_train)
y_pred_train_randforest = randforest.predict(X_train)
y_pred_test_randforest = randforest.predict(X_test)

In [25]:
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train, y_pred_train_randforest))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train, y_pred_train_randforest))
print('TRAIN : R2 Score:', r2_score(y_train, y_pred_train_randforest ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train, y_pred_train_randforest)))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred_test_randforest ))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred_test_randforest ))
print('TRAIN : R2 Score:', r2_score(y_test, y_pred_test_randforest ))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test_randforest )))

TRAIN : Mean Absolute Error: 125.68029971707114
TRAIN : Mean Squared Error: 65162.59149457975
TRAIN : R2 Score: 0.9959355278635372
TRAIN : Root Mean Squared Error: 255.26964467907214
----------------------------------------------------------
TEST : Mean Absolute Error: 325.4110218206038
TEST : Mean Squared Error: 455079.3310813409
TRAIN : R2 Score: 0.9720039583558293
TEST : Root Mean Squared Error: 674.5956797084762


#### Cross validation:

In [26]:
scores_randforest = cross_val_score(randforest, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error')
scores_randforest

array([-724.38372851, -689.13608518, -659.71628182])

## 6. K-NEAREST NEIGHBOR

In [27]:
neiclass = KNeighborsClassifier(n_neighbors=5)
neiclass.fit(X_train, y_train)

KNeighborsClassifier()

In [28]:
y_pred_train_neiclass = neiclass.predict(X_train)
y_pred_test_neiclass = neiclass.predict(X_test)

In [29]:
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train, y_pred_train_neiclass))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train, y_pred_train_neiclass))
print('TRAIN : R2 Score:', r2_score(y_train, y_pred_train_neiclass ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train, y_pred_train_neiclass)))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred_test_neiclass ))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred_test_neiclass ))
print('TRAIN : R2 Score:', r2_score(y_test, y_pred_test_neiclass ))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test_neiclass )))

TRAIN : Mean Absolute Error: 938.7277221604252
TRAIN : Mean Squared Error: 3212257.9096527006
TRAIN : R2 Score: 0.7996376069542659
TRAIN : Root Mean Squared Error: 1792.2772970867818
----------------------------------------------------------
TEST : Mean Absolute Error: 1124.1447287109133
TEST : Mean Squared Error: 4186854.0468421704
TRAIN : R2 Score: 0.7424287761543997
TEST : Root Mean Squared Error: 2046.1803554042274


#### Cross validation:

In [30]:
scores_neighclass = cross_val_score(neiclass, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error')
scores_neighclass

/home/ubuntu/.local/lib/python3.8/site-packages/sklearn/model_selection/_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(("The least populated class in y has only %d"


array([-2176.07415154, -2255.87156001, -2201.48994778])

## 7. BAYESIAN RIDGE

In [31]:
bay = BayesianRidge() 
bay.fit(X_train, y_train) 

BayesianRidge()

In [32]:
y_pred_train_bay = bay.predict(X_train)
y_pred_test_bay = bay.predict(X_test)

In [33]:
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train, y_pred_train_bay))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train, y_pred_train_bay))
print('TRAIN : R2 Score:', r2_score(y_train, y_pred_train_bay ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train, y_pred_train_bay)))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred_test_bay  ))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred_test_bay  ))
print('TRAIN : R2 Score:', r2_score(y_test, y_pred_test_bay ))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test_bay  )))

TRAIN : Mean Absolute Error: 806.1229448393493
TRAIN : Mean Squared Error: 1337815.1014316238
TRAIN : R2 Score: 0.91655469681619
TRAIN : Root Mean Squared Error: 1156.6395728279506
----------------------------------------------------------
TEST : Mean Absolute Error: 809.2507396301183
TEST : Mean Squared Error: 1367083.229800453
TRAIN : R2 Score: 0.91589835789378
TEST : Root Mean Squared Error: 1169.2233447038477


#### Cross validation:

In [34]:
scores_bay = cross_val_score(bay, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error')
scores_bay

array([-1183.19719059, -1155.18068928, -1134.31988814])

## 8. ELASTIC NET

In [35]:
elnet = ElasticNet(random_state=0)
elnet.fit(X_train, y_train)

ElasticNet(random_state=0)

In [36]:
y_pred_train_elnet = elnet.predict(X_train)
y_pred_test_elnet = elnet.predict(X_test)

In [37]:
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train, y_pred_train_elnet))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train, y_pred_train_elnet))
print('TRAIN : R2 Score:', r2_score(y_train, y_pred_train_elnet ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train, y_pred_train_elnet)))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred_test_elnet))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred_test_elnet))
print('TRAIN : R2 Score:', r2_score(y_test, y_pred_test_elnet ))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test_elnet)))

TRAIN : Mean Absolute Error: 1294.5469847091988
TRAIN : Mean Squared Error: 3714345.9792440995
TRAIN : R2 Score: 0.7683202065547686
TRAIN : Root Mean Squared Error: 1927.263858231171
----------------------------------------------------------
TEST : Mean Absolute Error: 1313.4465873819338
TEST : Mean Squared Error: 3763254.7808521762
TRAIN : R2 Score: 0.7684881945483683
TEST : Root Mean Squared Error: 1939.9110239524327


#### Cross validation:

In [38]:
scores_elnet = cross_val_score(elnet, X_train, y_train, cv=3, scoring='neg_root_mean_squared_error')
scores_elnet

array([-1940.16694213, -1942.87357928, -1900.81702381])

## Modify train_size

In [39]:
X_train2, X_test2, y_train2, y_test2 = train_test_split( X, y, train_size=0.9)

## 1.1 LINEAR REGRESSION

In [40]:
#We will try it with the model with the lower rmse, in this case : linear regression

In [41]:
#Train the model
lr_2 = LinearRegression()
lr_2.fit(X_train2, y_train2)

LinearRegression()

In [42]:
y_pred_train_lr_2 = lr_2.predict(X_train2)
y_pred_test_lr_2 = lr_2.predict(X_test2)

In [43]:
#TRAIN:
print('TRAIN : Mean Absolute Error:', metrics.mean_absolute_error(y_train2, y_pred_train_lr_2  ))
print('TRAIN : Mean Squared Error:', metrics.mean_squared_error(y_train2, y_pred_train_lr_2  ))
print('TRAIN : R2 Score:', r2_score(y_train2, y_pred_train_lr_2  ))
print('TRAIN : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_train2, y_pred_train_lr_2  )))
print ('----------------------------------------------------------')
#TEST:
print('TEST : Mean Absolute Error:', metrics.mean_absolute_error(y_test2, y_pred_test_lr_2 ))
print('TEST : Mean Squared Error:', metrics.mean_squared_error(y_test2, y_pred_test_lr_2 ))
print('TEST : R2 Score:', r2_score(y_test2, y_pred_test_lr_2))
print('TEST : Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test2, y_pred_test_lr_2 )))

TRAIN : Mean Absolute Error: 806.3361873891675
TRAIN : Mean Squared Error: 1347865.1008126426
TRAIN : R2 Score: 0.9158966740634362
TRAIN : Root Mean Squared Error: 1160.9759260263077
----------------------------------------------------------
TEST : Mean Absolute Error: 798.8502288813951
TEST : Mean Squared Error: 1304647.1082608048
TEST : R2 Score: 0.9210805907582567
TEST : Root Mean Squared Error: 1142.2114989181316


#### Cross validation:

In [44]:
scores_lr_2 = cross_val_score(lr_2, X_train2, y_train2, cv=3, scoring='neg_root_mean_squared_error')
scores_lr_2

array([-1140.2450363 , -1167.52161798, -1178.11441328])

# Lets introduce the second dataset

In [45]:
#import the dataset:
dmd_pred = pd.read_csv("../datasets/predict.csv",index_col="id")

In [46]:
dmd_pred.head()

carat      cut color clarity  depth  table     x     y     z
id                                                              
0    0.45  Premium     E     SI1   62.8   58.0  4.88  4.84  3.05
1    1.23    Ideal     H     SI1   61.0   56.0  6.96  6.92  4.23
2    0.33    Ideal     I      IF   61.8   55.0  4.46  4.47  2.76
3    0.51  Premium     D     VS2   58.0   60.0  5.29  5.26  3.06
4    0.40  Premium     E     VS2   62.2   59.0  4.71  4.74  2.94

In [47]:
# Same steps as with the dataset above:

In [48]:
dmd_pred = dmd_pred.drop(columns = ['x','y','z'])

In [49]:
#Value that are objcts have to be transformed to values that can be used with linear regression
#We create the dummies for the columns we want the type to change
dmd_cl1_dummy = pd.get_dummies(dmd_pred[['cut','color','clarity']], drop_first=True)
dmd_cl1_dummy.head()

dmd_pred = dmd_pred.drop(columns = ['cut','color','clarity'])

#I now join the dummies to the rest of the table
dmd_pred=dmd_pred.join(dmd_cl1_dummy)
dmd_pred.head()

carat  depth  table  cut_Good  cut_Ideal  cut_Premium  cut_Very Good  \
id                                                                         
0    0.45   62.8   58.0         0          0            1              0   
1    1.23   61.0   56.0         0          1            0              0   
2    0.33   61.8   55.0         0          1            0              0   
3    0.51   58.0   60.0         0          0            1              0   
4    0.40   62.2   59.0         0          0            1              0   

    color_E  color_F  color_G  color_H  color_I  color_J  clarity_IF  \
id                                                                     
0         1        0        0        0        0        0           0   
1         0        0        0        1        0        0           0   
2         0        0        0        0        1        0           1   
3         0        0        0        0        0        0           0   
4         1        0        0        0        0        0           0   

    clarity_SI1  clarity_SI2  clarity_VS1  clarity_VS2  clarity_VVS1  \
id                                                                     
0             1            0            0            0             0   
1             1            0            0            0             0   
2             0            0            0            0             0   
3             0            0            0            1             0   
4             0            0            0            1             0   

    clarity_VVS2  
id                
0              0  
1              0  
2              0  
3              0  
4              0

In [50]:
y_pred_predict_test = lr_2 .predict(dmd_pred)

In [51]:
y_pred_predict_test

array([ 843.18694456, 7163.36754768,  568.947967  , ..., 1340.19352651,
        -76.38601441, 4938.64859036])

In [52]:
dmd_pred['price'] = y_pred_predict_test
dmd_pred.head()

carat  depth  table  cut_Good  cut_Ideal  cut_Premium  cut_Very Good  \
id                                                                         
0    0.45   62.8   58.0         0          0            1              0   
1    1.23   61.0   56.0         0          1            0              0   
2    0.33   61.8   55.0         0          1            0              0   
3    0.51   58.0   60.0         0          0            1              0   
4    0.40   62.2   59.0         0          0            1              0   

    color_E  color_F  color_G  ...  color_I  color_J  clarity_IF  clarity_SI1  \
id                             ...                                              
0         1        0        0  ...        0        0           0            1   
1         0        0        0  ...        0        0           0            1   
2         0        0        0  ...        1        0           1            0   
3         0        0        0  ...        0        0           0            0   
4         1        0        0  ...        0        0           0            0   

    clarity_SI2  clarity_VS1  clarity_VS2  clarity_VVS1  clarity_VVS2  \
id                                                                      
0             0            0            0             0             0   
1             0            0            0             0             0   
2             0            0            0             0             0   
3             0            0            1             0             0   
4             0            0            1             0             0   

          price  
id               
0    843.186945  
1   7163.367548  
2    568.947967  
3   2303.372572  
4   1040.824437  

[5 rows x 21 columns]

In [58]:
#export

In [59]:
dmd_pred["price"].to_csv("final1.csv",header= True )